name: Tzcode-release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_windows:
      runs-on: windows-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3
